////////////////////////////////////////////////////////////////////////////////
//
//    Copyright (c) 2022 - 2023.
//    Haixing Hu, Qubit Co. Ltd.
//
//    All rights reserved.
//
////////////////////////////////////////////////////////////////////////////////
package ltd.qubit.commons.random.api;

import ltd.qubit.commons.random.Context;

/**
 * Interface for a {@link Randomizer} that is aware of the {@link Context
 * randomization context} it is invoked in.
 *
 * @param <T>
 *         the type generated by the randomizer
 * @author Mahmoud Ben Hassine (mahmoud.benhassine@icloud.com)
 */
public interface ContextAwareRandomizer<T> extends Randomizer<T> {

  void setContext(Context context);

}
