////////////////////////////////////////////////////////////////////////////////
//
//    Copyright (c) 2022 - 2023.
//    Haixing Hu, Qubit Ltd.
//
//    All rights reserved.
//
////////////////////////////////////////////////////////////////////////////////
package ltd.qubit.commons.random.api;

/**
 * Interface for custom randomizer.
 *
 * @param <T>
 *         the type generated by the randomizer
 * @author Mahmoud Ben Hassine (mahmoud.benhassine@icloud.com)
 */
@FunctionalInterface
public interface Randomizer<T> {

  /**
   * Generate a random value for the given type.
   *
   * @return a random value for the given type
   */
  T getRandomValue();

}
